### ISSUE TITLE
Already installed .Net but doesn't run 

### ISSUE THREAD

**Issue by AlperenYigitGungordu** [BedrockLauncher/BedrockLauncher#306] opened 2022-10-15 06:47 UTC
I don't  know what i am doing wrong but i installed .Net 6.0.0 then it didn't work it was same i restarted my pc same thing again then installed latest 6.0 SAME what am i gonna do

![image](https://user-images.githubusercontent.com/59205502/195973338-32ad2dc2-7cd1-4c20-b691-23a0fd0cc1b6.png)

**Comment by tresabhi** [comment] 2022-10-15 13:40
Duplicate of #296

**Closed by tresabhi** 2022-10-15 13:40 UTC
