### ISSUE TITLE
The latest release downloads minecraft preview 

### ISSUE THREAD

**Issue by Woof9999** [BedrockLauncher/BedrockLauncher#216] opened 2022-06-07 23:29 UTC

**Comment by Rayth** [comment] 2022-06-07 23:34
Download the latest launcher beta: https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/download/2022.4.17.21/build.zip

Duplicate of #150

**Closed by Rayth** 2022-06-07 23:34 UTC
