### ISSUE TITLE
0.13.X doesn't download

### ISSUE THREAD

**Issue by Hedwig7s** [BedrockLauncher/BedrockLauncher#159] opened 2022-02-18 12:11 UTC
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 427
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 452
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 353
Download start
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 427
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 452
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 353
Download start
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 427
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 452
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 353
Download start
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 427
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 452
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 353

**Comment by Rayth** [comment] 2022-02-18 13:18
duplicate of #81

**Closed by Rayth** 2022-02-18 13:18 UTC
