### ISSUE TITLE
Skin displayer blocks "Delete Skin Pack" prompt and soft locks the launcher

### ISSUE THREAD

**Issue by CoderMarcus** [BedrockLauncher/BedrockLauncher#64] opened 2021-09-03 05:46 UTC
When trying to delete a skin pack, the model that displays the skins appears above the prompt, making the buttons unresponsive. This soft locks the launcher as you cannot exit the prompt unless you restart the launcher.

![image of bug](https://user-images.githubusercontent.com/46655509/131956283-e41695cd-268d-4db9-9def-dc73735faa6d.png)

**Comment by NT690** [comment] 2021-09-03 05:59
Duplicate of #56 Which has a fix for beta 0.0.2.7

**Comment by CoolAbhi1290** [comment] 2021-09-03 16:21
Duplicate of #56

**Closed by CoolAbhi1290** 2021-09-03 16:21 UTC
