### ISSUE TITLE
Crashing on Install (Lutris wine f-shack 7.0  POP OS 22.04)

### ISSUE THREAD

**Issue by ssoufi-code** [BedrockLauncher/BedrockLauncher#213] opened 2022-06-07 00:19 UTC
This app is crashing when I click install and here is the output
![image](https://user-images.githubusercontent.com/85808224/172269832-18429a12-77bb-4c98-a5a5-96a1d0bf3edb.png)

**Comment by Rayth** [comment] 2022-06-07 00:26
Try using the latest beta which doesn't go through the installer:
https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

**Comment by ssoufi-code** [comment] 2022-06-07 00:51
I tried installing with the beta and this is the bug report 
Unhandled exception: 0xe0434352 in 32-bit code (0x7b0128a6).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b0128a6 ESP:00ebe534 EBP:00ebe5a8 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:00ebe540 EBX:00000000 ECX:00000010 EDX:00ebe5f8
 ESI:e0434352 EDI:00000005
Stack dump:
0x00ebe534:  00511410 0041164d 00a8f3f8 e0434352
0x00ebe544:  00000001 00000000 7b0128a6 00000005
0x00ebe554:  80004003 00000000 00000000 00000000
0x00ebe564:  00400000 00000000 02efef08 00000000
0x00ebe574:  00000000 00000000 023800b0 00ebe650
0x00ebe584:  00000001 00ebe60c 004b4570 0697eaec
Backtrace:
=>0 0x7b0128a6 AccessCheckByTypeAndAuditAlarmW+0x118a6() in kernelbase (0x00ebe5a8)
  1 0x00455e5e in bedrocklauncher.installer (+0x55e5e) (0x00ebe630)
  2 0x00558508 in bedrocklauncher.installer (+0x158508) (0x00ebe6c8)
  3 0x0e30985a (0x00ebe6d4)
  4 0x061df3ea in system.private.corelib (+0x25f3ea) (0x00ebe708)
  5 0x061df311 in system.private.corelib (+0x25f311) (0x00ebe714)
  6 0x0a843eb8 in windowsbase (+0x43eb8) (0x00ebe744)
  7 0x0a8941be in windowsbase (+0x941be) (0x00ebe77c)
  8 0x0a891be6 in windowsbase (+0x91be6) (0x00ebe7dc)
  9 0x0a891fc6 in windowsbase (+0x91fc6) (0x00ebe820)
  10 0x0a83b50c in windowsbase (+0x3b50c) (0x00ebe860)
  11 0x0a83aa7c in windowsbase (+0x3aa7c) (0x00ebe880)
  12 0x0a88f052 in windowsbase (+0x8f052) (0x00ebe8a0)
  13 0x0a88ef2d in windowsbase (+0x8ef2d) (0x00ebe8d4)
  14 0x0a890b81 in windowsbase (+0x90b81) (0x00ebe934)
  15 0x0a83a8d0 in windowsbase (+0x3a8d0) (0x00ebe9b4)
  16 0x0b69b609 (0x00ebe9f8)
  17 0x6ed88b7c AdjustWindowRect+0x2210c() in user32 (0x00ebea28)
  18 0x6ed89119 AdjustWindowRect+0x226a9() in user32 (0x00ebea88)
  19 0x6ed8b45a AdjustWindowRect+0x249ea() in user32 (0x00ebead8)
  20 0x6ed8b5de AdjustWindowRect+0x24b6e() in user32 (0x00ebeae8)
  21 0xf7b886b4 (0x00ebef78)
  22 0x7eb13854 (0x00ebf088)
  23 0x7eb13a7b (0x00ebf0a8)
  24 0x66b0ee55 NtBindCompositionSurface+0xde55() in win32u (0x00ebf0d8)
  25 0x6ed61385 AppendMenuA+0xeba5() in user32 (0x00ebf188)
  26 0x0c853eed (0x00ebf1cc)
  27 0x0a891d3f in windowsbase (+0x91d3f) (0x00ebf214)
  28 0x0a88fd66 in windowsbase (+0x8fd66) (0x00ebf224)
  29 0x0a88fd27 in windowsbase (+0x8fd27) (0x00ebf230)
  30 0x09b5c5db in presentationframework (+0x25c5db) (0x00ebf240)
  31 0x09b5b2d2 in presentationframework (+0x25b2d2) (0x00ebf260)
  32 0x09b58c28 in presentationframework (+0x258c28) (0x00ebf26c)
  33 0x0ac9232a (0x00ebf278)
  34 0x008e2abf MetaDataGetDispenser+0x4ce1f() in bedrocklauncher.installer (0x00ebf284)
  35 0x004fc4d8 in bedrocklauncher.installer (+0xfc4d8) (0x00ebf2b8)
  36 0x004fc7fc in bedrocklauncher.installer (+0xfc7fc) (0x00ebf334)
  37 0x0041602d in bedrocklauncher.installer (+0x1602d) (0x00ebf450)
  38 0x00416335 in bedrocklauncher.installer (+0x16335) (0x00ebf538)
  39 0x0041690c in bedrocklauncher.installer (+0x1690c) (0x00ebf818)
  40 0x00441e6e in bedrocklauncher.installer (+0x41e6e) (0x00ebf8b4)
  41 0x00896e9c MetaDataGetDispenser+0x11fc() in bedrocklauncher.installer (0x00ebf908)
  42 0x00879a97 in bedrocklauncher.installer (+0x479a97) (0x00ebf9b4)
  43 0x00879c72 in bedrocklauncher.installer (+0x479c72) (0x00ebf9e8)
  44 0x0087a515 in bedrocklauncher.installer (+0x47a515) (0x00ebfafc)
  45 0x0085ac10 in bedrocklauncher.installer (+0x45ac10) (0x00ebfb78)
  46 0x0085c8a5 in bedrocklauncher.installer (+0x45c8a5) (0x00ebfbdc)
  47 0x0085cd99 in bedrocklauncher.installer (+0x45cd99) (0x00ebfc38)
  48 0x0085cb57 in bedrocklauncher.installer (+0x45cb57) (0x00ebfcd0)
  49 0x0085a3f7 in bedrocklauncher.installer (+0x45a3f7) (0x00ebfd6c)
  50 0x008957ef in bedrocklauncher.installer (+0x4957ef) (0x00ebfec0)
  51 0x00895c0a in bedrocklauncher.installer (+0x495c0a) (0x00ebfee8)
  52 0x008e423c MetaDataGetDispenser+0x4e59c() in bedrocklauncher.installer (0x00ebff30)
  53 0x7b62d620 ActivateActCtx+0x22d10() in kernel32 (0x00ebff48)
  54 0x7bc59807 A_SHAFinal+0x39ab7() in ntdll (0x00ebff5c)
  55 0x7bc59ec0 A_SHAFinal+0x3a170() in ntdll (0x00ebffec)
0x7b0128a6 kernelbase+0x128a6: subl	$4,%esp
Modules:
Module	Address			Debug info	Name (102 modules)
PE	00400000-00c3f000	Export          bedrocklauncher.installer
PE	00ff0000-01956000	Deferred        shell32
PE	05f80000-06905000	Export          system.private.corelib
PE	06ee0000-098f6000	Deferred        bedrocklauncher.installer
PE	09900000-0a79a000	Export          presentationframework
PE	0a800000-0a9fc000	Export          windowsbase
PE	0aa20000-0aa2e000	Deferred        system.runtime
PE	0ab50000-0ac8e000	Deferred        system.xaml
PE	0aca0000-0acdd000	Deferred        system.io.packaging
PE	0acf0000-0ad2c000	Deferred        system.private.uri
PE	0ad30000-0b4ff000	Deferred        presentationcore
PE	0b540000-0b5ba000	Deferred        directwriteforwarder
PE	0b5e0000-0b5e8000	Deferred        system.runtime.extensions
PE	0b5f0000-0b5fc000	Deferred        system.runtime.interopservices
PE	0b610000-0b615000	Deferred        system.runtime.compilerservices.visualc
PE	0b620000-0b628000	Deferred        system.diagnostics.debug
PE	0b630000-0b642000	Deferred        system.threading
PE	0b650000-0b656000	Deferred        microsoft.win32.primitives
PE	0b670000-0b685000	Deferred        system.collections.nongeneric
PE	0b6a0000-0b6b3000	Deferred        microsoft.win32.registry
PE	0b6d0000-0b70a000	Deferred        system.collections
PE	0b720000-0b735000	Deferred        system.collections.specialized
PE	0b740000-0b751000	Deferred        system.componentmodel.primitives
PE	0b760000-0b768000	Deferred        system.threading.thread
PE	0b780000-0b866000	Deferred        presentationnative_cor3
PE	0b870000-0b94a000	Deferred        system.configuration.configurationmanager
PE	0b960000-0b968000	Deferred        system.runtime.interopservices.runtimeinformation
PE	0b970000-0b97a000	Deferred        system.xml.readerwriter
PE	0b980000-0c0fe000	Deferred        system.private.xml
PE	0c130000-0c154000	Deferred        system.net.webclient
PE	0c180000-0c189000	Deferred        system.componentmodel.eventbasedasync
PE	0c1a0000-0c1c8000	Deferred        system.memory
PE	0c1d0000-0c1d8000	Deferred        system.text.encoding.extensions
PE	0c1f0000-0c265000	Deferred        system.linq
PE	0c2b0000-0c2c5000	Deferred        system.objectmodel
PE	0c2d0000-0c377000	Deferred        system.security.cryptography.algorithms
PE	0c380000-0c39d000	Deferred        system.security.cryptography.primitives
PE	0c3b0000-0c455000	Deferred        system.componentmodel.typeconverter
PE	0c470000-0c4eb000	Deferred        system.text.regularexpressions
PE	0c4f0000-0c539000	Deferred        system.runtime.serialization.formatters
PE	0c540000-0c548000	Deferred        system.xml.xmlserializer
PE	0c550000-0c573000	Deferred        system.console
PE	0c5a0000-0c5ec000	Deferred        system.net.requests
PE	0c5f0000-0c620000	Deferred        system.net.primitives
PE	0c620000-0c62e000	Deferred        system.net.webheadercollection
PE	0c630000-0c638000	Deferred        system.threading.threadpool
PE	0c660000-0c67d000	Deferred        system.diagnostics.tracesource
PE	0c680000-0c690000	Deferred        system.windows.extensions
PE	0c6b0000-0c6b5000	Deferred        system.componentmodel
PE	0c6c0000-0c6f6000	Deferred        system.collections.concurrent
PE	0c790000-0c7d7000	Deferred        uiautomationtypes
PE	0c800000-0c840000	Deferred        system.diagnostics.process
PE	0c880000-0ca3a000	Deferred        wpfgfx_cor3
PE	0ca40000-0cdd4000	Deferred        d3dcompiler_47_cor3
PE	0d3c0000-0d423000	Deferred        mscms
PE	0ded0000-0df11000	Deferred        presentationframework.classic
PE	0df50000-0df5c000	Deferred        uiautomationprovider
PE	0df90000-0df98000	Deferred        system.runtime.loader
PE	0e2d0000-0e2d6000	Deferred        presentationframework-systemxml
PE	0e320000-0e329000	Deferred        system.diagnostics.stacktrace
PE	10000000-101ea000	Deferred        bedrocklauncher.localization
PE	18b10000-18c15000	Deferred        system.reflection.metadata
PE	18c20000-18cb2000	Deferred        system.collections.immutable
PE	61740000-61784000	Deferred        advapi32
PE	61940000-619d7000	Deferred        wininet
PE	62440000-62761000	Deferred        d3d9
PE	62d40000-62ef3000	Deferred        windowscodecs
PE	62fc0000-63055000	Deferred        rpcrt4
PE	63480000-6348d000	Deferred        version
PE	637c0000-6386f000	Deferred        urlmon
PE	63b00000-63b0e000	Deferred        windowscodecsext
PE	63bc0000-63bda000	Deferred        shcore
PE	64a40000-64a9d000	Deferred        shlwapi
PE	64ec0000-64ff8000	Deferred        oleaut32
PE	65580000-6558d000	Deferred        wtsapi32
PE	66240000-66257000	Deferred        bcrypt
PE	66b00000-66b3f000	Dwarf           win32u
PE	67c40000-67c7e000	Deferred        mscoree
PE	682c0000-682eb000	Deferred        winevulkan
PE	68500000-6855c000	Deferred        combase
PE	68700000-68736000	Deferred        uxtheme
PE	68e00000-68e11000	Deferred        aclui
PE	69940000-6996b000	Deferred        propsys
PE	69ac0000-69acd000	Deferred        vulkan-1
PE	6a280000-6a337000	Deferred        msvcrt
PE	6a400000-6a53d000	Deferred        ole32
PE	6bc00000-6bc2c000	Deferred        sechost
PE	6bcc0000-6bd47000	Deferred        setupapi
PE	6be40000-6bec0000	Deferred        dwrite
PE	6c9c0000-6ca4d000	Deferred        gdi32
PE	6cc40000-6cda3000	Deferred        comctl32
PE	6d780000-6d7a8000	Deferred        ws2_32
PE	6ec40000-6ec4d000	Deferred        dwmapi
PE	6ed00000-6eef8000	Dwarf-4         user32
PE	6fa80000-6fb01000	Deferred        dbghelp
PE	70940000-70960000	Deferred        mpr
PE	70b40000-70c23000	Deferred        ucrtbase
PE	71200000-7121c000	Deferred        imm32
PE	7b000000-7b0fa000	Dwarf-2-4       kernelbase
PE	7b600000-7b826000	Dwarf-2-4       kernel32
PE	7bc00000-7bcae000	Dwarf-2-4       ntdll
PE	7e250000-7e254000	Deferred        winex11
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000054    0     
	00000068    0     
	0000008c    0     
	000000a4    0     
	000000d0    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000058    0     
	0000005c    0     
	000000b0    0     
00000060 winedevice.exe
	00000064    0     
	0000006c    0     
	00000070    0     
	00000074    0     
	00000078    0     
	0000007c    0     
	00000080    0     
00000084 plugplay.exe
	00000088    0     
	00000090    0     
	00000094    0     
	00000098    0     
0000009c svchost.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
000000b4 explorer.exe
	000000b8    0     
	000000bc    0     
	000000c0    0     
	000000fc    0     
	00000108    0     
	0000010c    0     
	00000110    0     
000000c8 rpcss.exe
	000000cc    0     
	000000d8    0     
	000000dc    0     
	000000e0    0     
	000000e4    0     
	000000e8    0     
	000000f8    0     
	00000238    0     
	000002d0    0     
000000f0 explorer.exe
	000000f4    0     
	00000114    0     
0000023c start.exe
	00000240    0     
00000244 (D) Z:\run\user\1000\doc\2c38b554\BedrockLauncher.Installer.exe
	["Z:\run\user\1000\doc\2c38b554\BedrockLauncher.Installer.exe" ]
	00000248    0 <== 
	0000024c    0     
	00000250    0     
	00000254    2     
	00000258    0     
	00000260    0     
	00000264    0     
	00000268    0     
	0000026c    0     
	00000270    0     
	00000274   -2     
	00000278   -2     
	0000027c   -2     
	00000280   -2     
	00000284   -2     
	00000288   -2     
	0000028c   -2     
	00000290   -2     
	00000294   -2     
	00000298   -2     
	0000029c    0     
	000002a0    0     
	000002a4    0     
	000002a8    0     
	000002bc    0     
000002b4 conhost.exe
	000002b8    0     
000002c0 explorer.exe
	000002c4    0     
	000002c8    0     
	000002cc    0     
System information:
    Wine build: wine-7.5 ( TkG Staging Esync Fsync )
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.17.5-76051705-generic

**Comment by Rayth** [comment] 2022-06-07 00:53
You don't run the installer... you literally extract the build.zip folder from the link above and run bedrock_launcher.exe

Also could be an issue since you're using WINE on Linux. Not sure if anyone has confirmed if this works or not

**Comment by ssoufi-code** [comment] 2022-06-07 00:58
file:///home/computeruser/Documents/backtrace.txt

**Comment by ssoufi-code** [comment] 2022-06-07 01:04
It wouldn't launch, it would just spit out 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
The application to execute does not exist: 'Z:\run\user\1000\doc\31e010a9\Bedro
ckLauncher.dll'.
00fc:err:eventlog:ReportEventW L"Description: A .NET application failed.\nApplication: BedrockLauncher.exe\nPath: Z:\\run\\user\\1000\\doc\\31e010a9\\BedrockLauncher.exe\nMessage: The application to execute does not exist: 'Z:\\run\\user\\1000\\doc\\31e010a9\\BedrockLauncher.dll'.\n\n"

**Comment by ssoufi-code** [comment] 2022-06-07 01:17
It seems like the issue was it was not reading dll files, I'll retest and get back to you

**Comment by Rayth** [comment] 2022-06-07 01:17
I mean the FAQ does say that only windows is supported so trying to run this on linux via wine may not work at all.
https://bedrocklauncher.github.io/faq

**Comment by TresAbhi** [comment] 2022-06-07 14:24
Bedrock launcher was ran on a non-windows machines. Closing as that is unsupported and is mentioned clearly in the FAQ.

**Closed by TresAbhi** 2022-06-07 14:24 UTC
