### ISSUE TITLE
Bedrock Isnt Opening

### ISSUE THREAD

**Issue by hackeroyuncu09** [BedrockLauncher/BedrockLauncher#208] opened 2022-05-19 07:08 UTC
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.33.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.33.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs içinde: satır 596
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs içinde: satır 562
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.33.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.33.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs içinde: satır 596
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs içinde: satır 562

**Comment by TresAbhi** [comment] 2022-05-19 12:06
Duplicate of #73

**Closed by TresAbhi** 2022-05-19 12:06 UTC
