### ISSUE TITLE
beta 0.0.2.3 App Re-register faild when loading to previous ver

### ISSUE THREAD

**Issue by gituser245** [BedrockLauncher/BedrockLauncher#44] opened 2021-07-29 11:26 UTC
beta 0.0.2.3 App Re-register faild
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/6899850/Log.txt)
how the error occurs    attempting to load a version of minecraft older than the version that has been loaded will resoult in an error

i loaded version1 and i load version2 i cant go back to version1 the Re-register faild error will be given but i can load version3

**Comment by CoolAbhi1290** [comment] 2021-07-29 14:36
Duplicate of #39

**Closed by CoolAbhi1290** 2021-07-29 14:36 UTC
