### ISSUE TITLE
I HAVE AN ISSUE IT SAYS Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies

### ISSUE THREAD

**Issue by ORGINRISHITH** [BedrockLauncher/BedrockLauncher#170] opened 2022-03-06 08:27 UTC
HI AFTER THE INSTALLATION IT SAYS Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies 
HERE IS THE LOG[https://drive.google.com/file/d/16EKX7UZ58FlpztpKi0IcrEmKqEkrrWgi/view?usp=sharing](url)

**Comment by Rayth** [comment] 2022-03-06 14:56
Duplicate of #84

**Closed by Rayth** 2022-03-06 14:56 UTC
