### ISSUE TITLE
I cant uninstall it

### ISSUE THREAD

**Issue by xxyz30** [BedrockLauncher/BedrockLauncher#126] opened 2022-01-13 07:36 UTC
![图片](https://user-images.githubusercontent.com/81208875/149285750-f3d6440e-3416-43e2-81b8-b8d86449c3cc.png)
Double-clicking on it doesn't work
![图片](https://user-images.githubusercontent.com/81208875/149285929-3c55d6cb-d59d-42cb-8a6c-146ba52147c9.png)

**Comment by TresAbhi** [comment] 2022-01-13 13:11
Can you try doing that trough the settings app? Or even try the control panel.

**Comment by xxyz30** [comment] 2022-01-16 16:01
picture 1 is the control panel,
and settings app can't uninstall it either

**Comment by xxyz30** [comment] 2022-01-16 16:30
https://youtu.be/yNsdhl-ASNw
here is video.
Not only can not uninstall, and can not start, often did not respond.

**Comment by xxyz30** [comment] 2022-01-16 16:40
And uninstall.exe only delete "BedrockLauncher.exe"
I can't be certain about the other files.
![图片](https://user-images.githubusercontent.com/81208875/149669037-2b7c5fd1-2064-4f6c-8a12-b61f70261168.png)
1.17GB has leave

**Comment by Rayth** [comment] 2022-01-16 20:20
This is actually a duplicate of #113 although in this case, it saves your setting files etc which is perfectly normal.

**Closed by Rayth** 2022-01-16 20:20 UTC
