### ISSUE TITLE
Crash when creating profile

### ISSUE THREAD

**Issue by Fabrico84** [BedrockLauncher/BedrockLauncher#200] opened 2022-04-29 14:27 UTC
when I try to open the launcher from this version https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21 it crashes when I am told to make a new account (by pressing the create new account button)
![Screenshot (28)](https://user-images.githubusercontent.com/104581143/165964140-15d0250e-383f-4789-b13f-4f8d92192540.png)

**Comment by Rayth** [comment] 2022-04-29 14:52
Updated to remove the duplicate issue. When it crashes, does it give you the "create" screen again if you re-open? Do you have a log from that crash? Iirc it happened to me but when i re-opened it was fine

**Comment by Fabrico84** [comment] 2022-04-29 15:20
I reopened the application file from the build is there a different way to reopen it? Also when I reopen it it starts from the start message:

Welcome to Bedrock edition Launcher!  

Something like that i don't remember excactly the message. Also there no option to find the log, the app just closes a few seconds i pressed the create button. Lastly beetween the time I pressed the create button and the crash the appdid not respond at all (it was in a frozen state).

**Comment by Fabrico84** [comment] 2022-04-29 15:48
this is the latest log in there
[Log_2022-04-29_18-45-48.log](https://github.com/BedrockLauncher/BedrockLauncher/files/8592061/Log_2022-04-29_18-45-48.log)
:

**Comment by Rayth** [comment] 2022-04-29 15:54
ok if you open it again and leave it for a few minutes does it load at all? even if it looks like it freezes up just leave it for ~5-10mins see if it loads up. if not, post a new log

**Comment by Fabrico84** [comment] 2022-04-29 15:57
So after I open it and it closes wait to see if it will reopen? Because after it freezes the app closes.

**Comment by Rayth** [comment] 2022-04-29 16:01
yeah and if it closes a second time, post log again

**Comment by Fabrico84** [comment] 2022-04-29 17:15
[Log_2022-04-29_20-11-14.log](https://github.com/BedrockLauncher/BedrockLauncher/files/8592538/Log_2022-04-29_20-11-14.log) Same thing happened...

**Comment by Fabrico84** [comment] 2022-05-18 20:17
Hello, sorry for asking again after so many days. I was just wandering if we could try to solve this now that i am more time flexible.

**Comment by TresAbhi** [comment] 2022-05-18 20:23
@Fabrico84 create an account via an older version then upgrade to this version

**Comment by Fabrico84** [comment] 2022-05-20 14:55
Could you help me further? I cant seem to figure out how to perform this.

**Comment by TresAbhi** [comment] 2022-05-20 15:40
When installing Bedrock Launcher, do not select the beta version. Create a profile after installation, and in settings, turn on betas. Update to the beta version and, voila, no crashes.

**Comment by Fabrico84** [comment] 2022-05-20 17:00
Ok that fixed the problem, but it still fails registering the app.

**Comment by Rayth** [comment] 2022-05-20 17:13
Uninstall minecraft from your computer via control panel then click play
from app

**Comment by Fabrico84** [comment] 2022-05-20 18:58
I can’t find Minecraft in the control panel, I can only find the launcher.

**Comment by Fabrico84** [comment] 2022-05-20 19:17
Minecraft got uninstalled on its own weird. Anyways here is the log for app registration failed:

BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.18.3104.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.18.3104.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 473
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 219
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 230
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 62

**Comment by Rayth** [comment] 2022-05-21 02:09
Now a duplicate of #73

**Closed by Rayth** 2022-05-21 02:09 UTC
Labels: affects 2022.4.17.21
