### ISSUE TITLE
I can install it, but I can't make a micra. 

### ISSUE THREAD

**Issue by kazaminosuke** [BedrockLauncher/BedrockLauncher#156] opened 2022-02-15 21:46 UTC
Error-2147024894 ErrorApp-register failed

**Comment by kazaminosuke** [comment] 2022-02-15 21:50
https://drive.google.com/file/d/1UXuIErkRvJ94RxjGVOXodF3t1uoWH_3A/view?usp=sharing An errorVideo

**Comment by Rayth** [comment] 2022-02-15 21:51
That video is not publically shared.

**Comment by TresAbhi** [comment] 2022-02-16 13:14
Duplicate of #39.

**Closed by TresAbhi** 2022-02-16 13:14 UTC
