### ISSUE TITLE
app re_register failed

### ISSUE THREAD

**Issue by Giuliohus96** [BedrockLauncher/BedrockLauncher#144] opened 2022-02-12 08:23 UTC
can i able to fix this eror ? pls hey me how i need this
![image](https://user-images.githubusercontent.com/99075199/153703534-1fc4ebce-b54d-4c38-9207-38cc2dd63c5d.png)

**Comment by Rayth** [comment] 2022-02-12 14:07
You can't use latest release setting at the moment. Also clicking "view crash report" will provide us the log.

**Comment by Giuliohus96** [comment] 2022-02-12 18:31
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/8054269/Log.txt)
i think this is the log

**Comment by Rayth** [comment] 2022-02-12 18:42
So firstly the Microsoft.Store.Engatement missing is a duplicate of #73 

Secondly, you CANNOT USE LATEST RELEASE because the launcher sees the new "Previews" as release and cannot launch them.

**Closed by Rayth** 2022-02-12 18:42 UTC
