### ISSUE TITLE
HOW DO I FIX THIS

### ISSUE THREAD

**Issue by ItsAlmighty09** [BedrockLauncher/BedrockLauncher#115] opened 2021-12-09 17:53 UTC
HOW DO I FIX THIS:

Log:
```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
```

**Comment by ItsAlmighty09** [comment] 2021-12-09 17:54
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562

**Comment by TresAbhi** [comment] 2021-12-09 18:42
Can you please provide more information as to what's happening? Until then, I'm marking this as invalid.

**Comment by Rayth** [comment] 2021-12-09 19:05
Duplicate of #73

**Closed by Rayth** 2021-12-09 19:05 UTC
Labels: invalid
