### ISSUE TITLE
Failed to re-register the app

### ISSUE THREAD

**Issue by EnderCat272** [BedrockLauncher/BedrockLauncher#233] opened 2022-06-26 15:12 UTC
BedrockLauncher.Exceptions.PackageDeregistrationFailedException: Value does not fall within the expected range.
 ---> System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Management.Deployment.IPackageManager2Methods.RemovePackageAsync(IObjectReference _obj, String packageFullName, RemovalOptions removalOptions)
   at BedrockLauncher.Handlers.PackageHandler.UnregisterPackage(MCVersion v, Boolean keepVersion) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 0
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.UnregisterPackage(MCVersion v, Boolean keepVersion) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 314
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 61

**Comment by TresAbhi** [comment] 2022-06-26 15:17
Duplicate of #39

**Closed by TresAbhi** 2022-06-26 15:17 UTC
