### ISSUE TITLE
i couldn't able to uninstall the app from my pc 

### ISSUE THREAD

**Issue by ghost** [BedrockLauncher/BedrockLauncher#236] opened 2022-07-02 07:11 UTC
![image](https://user-images.githubusercontent.com/105100132/176990633-b5ff1249-abc2-432a-812d-c745b963d8ef.png)

someone help me!

**Comment by NT690** [comment] 2022-07-02 23:10
Duplicate of #113

**Comment by NT690** [comment] 2022-07-02 23:17
On second thought, it might be best to give more details about what is going wrong, such as if the uninstaller doesn't open or if the uninstaller just doesn't uninstall the launcher.

**Comment by ShivaShankar2003** [comment] 2022-07-03 04:04
I couldn't able to find the uninstaller 😅

**Comment by Rayth** [comment] 2022-07-04 10:05
Files are removed from PC it just doesn't remove from program list.

Latest release doesn't use an installer so is no longer an issue.

**Closed by Rayth** 2022-07-04 10:05 UTC
