### ISSUE TITLE
Installation Fails because of Package Installation Flags

### ISSUE THREAD

**Issue by CubeIR** [BedrockLauncher/BedrockLauncher#70] opened 2021-09-15 11:40 UTC
I get the following error in beta version (same happens out of beta too):

```
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.17.3025.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<UnregisterPackages>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 276
```
   
   
   is there a way to fix it? or a workaround?
Is it possible to download an older version of the launcher?
it didn't happen before.

**Comment by TresAbhi** [comment] 2021-09-15 14:50
Duplicate of #39

**Comment by CarJem** [comment] 2021-09-15 18:03
I disagree... although similar... to narrow the vage #39 issue down... I shall reopen this

**Comment by TresAbhi** [comment] 2021-09-15 22:50
Sorry about that

**Closed** 2022-07-04 10:18 UTC
Labels: bug, investigating
