### ISSUE TITLE
Object reference not set to an instance of an object. (Possible duplicate)

### ISSUE THREAD

**Issue by PageNotFound40** [BedrockLauncher/BedrockLauncher#224] opened 2022-06-14 19:29 UTC
BedrockLauncher.Exceptions.AppLaunchFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 58
   --- End of inner exception stack trace --- 
i tryed the "fix" you wanted me to do

**Comment by Rayth** [comment] 2022-06-14 19:46
Can you provide the log file.

**Comment by NT690** [comment] 2022-06-15 00:14
i think this is a duplicate of #53

**Comment by Rayth** [comment] 2022-06-15 00:26
Still want a log to verify that as i haven't seen any reports of this error on the beta version

**Comment by TresAbhi** [comment] 2022-06-19 14:04
Closing due to inactivity

**Closed by TresAbhi** 2022-06-19 14:04 UTC
Labels: question
