### ISSUE TITLE
Support For Faild Re-Regiser App

### ISSUE THREAD

**Issue by THOBY555** [BedrockLauncher/BedrockLauncher#45] opened 2021-07-31 22:05 UTC
Hi, i HAVE Problem When I Launching MCW10 Its Didnt Luanch And Sying In The Crah Log:

Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Removing package: Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe
Package is in development mode
Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.
App re-register failed:
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<RemovePackage>d__25.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 547

PLS Help

**Comment by CoolAbhi1290** [comment] 2021-08-01 01:37
Duplicate of #39

**Closed by CoolAbhi1290** 2021-08-01 01:37 UTC

**Comment by THOBY555** [comment] 2021-08-02 23:08
> Duplicate of #39

![esfesdfersgferdsg](https://user-images.githubusercontent.com/71563419/127934451-46e6f5ef-07bb-4ca5-a70c-3e29e5347aec.jpg)
Why It is Not Working For ME :(

**Comment by CarJem** [comment] 2021-08-03 22:54
Based on what I've been seeing lately, if you are having app re-registering failed issues here are my suggestions:
1. Make Sure Minecraft Bedrock is not Installed
2. Make Sure Nobody Else on your Machine has Bedrock Installed
3. Send me a stack trace of the error

In regards to my second point... There is nothing I can do about this one... this is a Windows Store / APPX Package Limitation.... Sorry Guys... I'd make it possible if it was possible.

**Comment by THOBY555** [comment] 2021-08-04 00:40
ok

**Comment by THOBY555** [comment] 2021-08-04 00:49
> Based on what I've been seeing lately, if you are having app re-registering failed issues here are my suggestions:
> 
> 1. Make Sure Minecraft Bedrock is not Installed
> 2. Make Sure Nobody Else on your Machine has Bedrock Installed
> 3. Send me a stack trace of the error
> 
> In regards to my second point... There is nothing I can do about this one... this is a Windows Store / APPX Package Limitation.... Sorry Guys... I'd make it possible if it was possible.

And After Deleting That What I Do ?
