### ISSUE TITLE
wont start minecraft

### ISSUE THREAD

**Issue by urmom2025** [BedrockLauncher/BedrockLauncher#226] opened 2022-06-17 07:33 UTC
hi i am trying to launch minecraft
when ever i click start it just closes the app

**Comment by Rayth** [comment] 2022-06-17 08:44
Use latest launcher beta: https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

Duplicate of #150

**Closed by Rayth** 2022-06-17 08:44 UTC
