### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by hiimarandomguy** [BedrockLauncher/BedrockLauncher#120] opened 2021-12-28 07:54 UTC
Also an error when I try to play any version of Bedrock Launcher 
It says : System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.18.203.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
   at BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 549
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 277
Any help please ?

**Comment by Rayth** [comment] 2021-12-28 11:32
duplicate of #73

**Closed by Rayth** 2021-12-28 11:32 UTC
