### ISSUE TITLE
The 'New Update' banner is visible

### ISSUE THREAD

**Issue by Mcfly2340** [BedrockLauncher/BedrockLauncher#243] opened 2022-07-04 19:17 UTC
This wasn't present in the lite version before the pre-release but just here to let you know

![image](https://user-images.githubusercontent.com/71077562/177208011-157af0f5-7fde-4beb-9f2f-a320299d246c.png)

source of previous version: https://twitter.com/carter5467_99/status/1543359861626388482

**Comment by Rayth** [comment] 2022-07-04 19:56
Duplicate of #190

**Closed by Rayth** 2022-07-04 19:56 UTC
