### ISSUE TITLE
Fail to find download link

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [BedrockLauncher/BedrockLauncher#101] opened 2021-11-10 15:25 UTC
I've been playing a beta world, yesterday it started saying failed to find download link. Saw the update today and hoped that'd fix the issue, but still getting the same thing. Other instances work fine.

> Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.6
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 426
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 445
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 451
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__21.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 363

**Comment by TresAbhi** [comment] 2021-11-10 15:32
Duplicate of #81

**Closed** 2021-11-10 15:33 UTC
