### ISSUE TITLE
Unable to Change Installation Picture 

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#256] opened 2022-07-25 04:24 UTC
Even though I click the "Save" button after I change the picture of an installation, the picture is still the same

**Comment by NT690** [comment] 2022-07-25 04:25
This is the same for both creating and editing installation data

**Comment by tresabhi** [comment] 2022-07-25 07:55
This was fixed in #244, are you sure you're on the latest beta?

**Comment by Rayth** [comment] 2022-07-25 11:38
It was fixed, but a release wasn't pushed with the fix. So it is fixed in the development version. Either way it's a duplicate of #244

**Closed by Rayth** 2022-07-25 11:38 UTC
