### ISSUE TITLE
Launcher cant launch the game on first install

### ISSUE THREAD

**Issue by TypicalShavonne** [BedrockLauncher/BedrockLauncher#112] opened 2021-12-07 00:35 UTC
`Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Version list local cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\versions.json'.
File name: 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromLocalCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 130
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 109
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 109
Version list technical cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt'.
File name: 'C:\Users\tranh\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionTextDb.Read(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 50
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromTechCache() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 151
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/6e362967-4f60-4d4b-abf5-61f05bc428dd?P1=1638851167&P2=404&P3=2&P4=SyQhiqeiezR9TDXcbBL%2buc2bmvGbE3af1cZnsqC9bqxSFj9IoMzOycncJ4zvw%2fXpMyYK%2fEZyQm%2bS1jMrXGEqwQ%3d%3d
Actual download started
Download complete
Extraction started
Extracted successfully
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.18.102.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.18.102.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
`
i cant launcher the game, windows version: 
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000

**Comment by TypicalShavonne** [comment] 2021-12-07 00:36
https://paste.hahota.net/CEBNXwan
uploaded log to a bin

**Comment by Rayth** [comment] 2021-12-07 00:54
Duplicate of #73

**Closed by Rayth** 2021-12-07 00:54 UTC
