### ISSUE TITLE
Version list JSON file fails to load

### ISSUE THREAD

**Issue by YepImZynx92** [BedrockLauncher/BedrockLauncher#131] opened 2022-01-26 11:35 UTC
this is the log:

```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Version list local cache load failed:
System.IO.FileNotFoundException: Файл 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\versions.json' не найден.
Имя файла: 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\versions.json'
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path)
   в System.IO.File.OpenText(String path)
   в BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:строка 134
   в BedrockLauncher.Downloaders.VersionDownloader.LoadFromLocalCache(ObservableCollection`1 versions) в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 130
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Version list user cache load failed:
System.IO.FileNotFoundException: Файл 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\local_versions.json' не найден.
Имя файла: 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path)
   в System.IO.File.OpenText(String path)
   в BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:строка 134
   в BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 109
Version list user cache load failed:
System.IO.FileNotFoundException: Файл 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\local_versions.json' не найден.
Имя файла: 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path)
   в System.IO.File.OpenText(String path)
   в BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:строка 134
   в BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 109
Version list technical cache load failed:
System.IO.FileNotFoundException: Файл 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt' не найден.
Имя файла: 'C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt'
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   в System.IO.StreamReader..ctor(String path)
   в System.IO.File.OpenText(String path)
   в BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionTextDb.Read(String filePath) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:строка 51
   в BedrockLauncher.Downloaders.VersionDownloader.LoadFromTechCache() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 151
Файл "C:\Users\Данил\AppData\Roaming\.minecraft_bedrock\installations\ThisIsZynx92\Latest Release\packageData\skin_packs\kfpuusup\pack_icon.png" уже существует.
```

**Comment by Rayth** [comment] 2022-01-26 14:46
Duplicate of #96

**Closed by Rayth** 2022-01-26 14:46 UTC
Labels: bug, affects 0.0.2.6
