### ISSUE TITLE
EXE file could not launch.

### ISSUE THREAD

**Issue by hatsuyuki2333** [BedrockLauncher/BedrockLauncher#321] opened 2022-12-04 05:56 UTC
I'm using Windows10 and properly installed .NET Runtime 6.0. However,the program didn't launch(it stuck and closed at once when I opened it)
I have installed .NET runtime and SDK at the same time,I don't know if this has an impact on it.
[Log_2022-12-04_13-37-42.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10147953/Log_2022-12-04_13-37-42.log)

**Comment by Rayth** [comment] 2022-12-04 05:59
Did you install the .Net DESKTOP runtime though?

**Comment by hatsuyuki2333** [comment] 2022-12-04 06:52
Yes.
> .NET Desktop Runtime 6.0.11   The .NET Desktop Runtime enables you to run existing Windows desktop applications. ''This release includes the .NET Runtime; you don't need to install it separately.''

**Comment by hatsuyuki2333** [comment] 2022-12-04 06:54
I tried to re-run .NET installer to repair but  it still doesn't work.

**Comment by AldoTN** [comment] 2022-12-26 18:43
> I tried to re-run .NET installer to repair but it still doesn't work.

Download .NET 6.0.6 instead of 6.0.1X

https://dotnet.microsoft.com/es-es/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer
(this site is for spanish, change the url accordingly)

**Comment by Rayth** [comment] 2022-12-26 18:44
> > I tried to re-run .NET installer to repair but it still doesn't work.
> 
> Download .NET 6.0.6 instead of 6.0.1X
> 
> https://dotnet.microsoft.com/es-es/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer (this site is for spanish, change the url accordingly)

i used 6.0.11 fine.

**Comment by Rayth** [comment] 2022-12-26 18:45
this one is actually a duplicate of #269

**Closed by Rayth** 2022-12-26 18:45 UTC
