### ISSUE TITLE
Unhandled exception occurred: reference to an object not set to an object instance

### ISSUE THREAD

**Issue by SAB236YT** [BedrockLauncher/BedrockLauncher#284] opened 2022-09-01 14:31 UTC
title

**Comment by Rayth** [comment] 2022-09-01 14:46
Can you please provide a log file.
It will either be log.txt in the folder where the launcher is installed, or in the data/logs folder.

**Comment by tresabhi** [comment] 2022-09-01 14:50
Duplicate of #53

Do not use anything other than English numbers and letters for installation and profile names.

**Closed by tresabhi** 2022-09-01 14:50 UTC
