### ISSUE TITLE
Cannot Delete Duplicates of "Latest Release" "Latest Beta" and "Latest Preview"

### ISSUE THREAD

**Issue by TheNatBoi** [BedrockLauncher/BedrockLauncher#253] opened 2022-07-25 03:56 UTC
When you duplicate any of the "Latest ..." installations, their duplicates cannot be edited or deleted.

**Comment by tresabhi** [comment] 2022-07-25 04:07
Can you please provide a log?

**Comment by NT690** [comment] 2022-07-25 04:10
I don't see the need for a log as the installations simply don't have a "delete" or "edit" button.

**Comment by NT690** [comment] 2022-07-25 04:11
Here it is if there is some obvious reason I am missing
```2022-07-24 21:09:51.6748|DEBUG||Version: 2022.7.4.195
2022-07-24 21:09:51.7216|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-07-24 21:09:51.7216|DEBUG||Git Branch: lite
2022-07-24 21:09:51.7216|DEBUG||Git Commit: 3ed563d
2022-07-24 21:09:51.7216|DEBUG||Git Sha: 3ed563d2826badcfafa0817d0df8700c778f1e42
2022-07-24 21:09:51.7216|DEBUG||Application Starting...
2022-07-24 21:09:51.9427|DEBUG||Application Initalization Started!
2022-07-24 21:09:51.9427|DEBUG||Application Initalization Finished!
2022-07-24 21:09:52.9020|DEBUG||Preparing Application...
2022-07-24 21:09:57.8444|DEBUG||Checking for updates
2022-07-24 21:09:58.8698|DEBUG||Current tag: 2022.7.4.195
2022-07-24 21:09:58.8698|DEBUG||Latest tag: 2022.7.4.195
2022-07-24 21:09:58.8698|DEBUG||Preparing Application: DONE
```

**Comment by tresabhi** [comment] 2022-07-25 04:13
Is that the whole log? It doesn't seem to capture any errors.

**Comment by NT690** [comment] 2022-07-25 04:15
that is the full log, but as I said before, in the dropdown, there is simply no button to "delete" or "edit"

**Comment by Rayth** [comment] 2022-07-25 11:42
It's not a "bug" per se. When you duplicate one of the "latest" ones, you're basically creating another protected one. Now being unable to re-name it is a problem since it'll just pull files from "Latest Release" or whichever you duplicated anyway, therefore duplicating it is a pointless endeavor.

A Better solution to this, would have it popup asking for a new name whenever you duplicate something

**Comment by gritty-Kitty** [comment] 2024-07-21 20:51
Downloaded latest 2024.5.31.2.
Confirmed this issue still exists.
How can I delete a DUPLICATE of LATEST RELEASE.

![image](https://github.com/user-attachments/assets/12c71ca8-cde6-43f7-b453-394f90596ff9)

**Comment by Rayth** [comment] 2024-07-21 21:28
You can't from inside the launcher. you'd need to delete/edit files manually. We know it's still an issue otherwise we would've closed this

**Closed** 2024-08-14 01:11 UTC
Labels: enhancement, affects 2022.7.3.63, affects 2022.7.4.195
