### ISSUE TITLE
Getting this issue while trying to launch any minecraft Version

### ISSUE THREAD

**Issue by SecretGamerV071** [BedrockLauncher/BedrockLauncher#157] opened 2022-02-16 11:02 UTC
Log.txt:

Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.6
Removing package: Microsoft.MinecraftUWP_1.18.1004.0_x64__8wekyb3d8bbwe
Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.18.1004.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
App launch failed:
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.18.1004.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<UnregisterPackages>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 276

**Comment by Rayth** [comment] 2022-02-16 11:55
Try uninstall minecraft manually first in control panel, then install it using the launcher. Please note the current launcher build sees the Preview as a release and you need to create an installation to specify 1.18.10 as the latest version (or any previous version you wish to install)

**Comment by TresAbhi** [comment] 2022-02-16 13:13
Duplicate of #39

**Closed by TresAbhi** 2022-02-16 13:13 UTC
