### ISSUE TITLE
App Re-Register Fails

### ISSUE THREAD

**Issue by krack-jack** [BedrockLauncher/BedrockLauncher#72] opened 2021-09-20 03:44 UTC
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Removing package: Microsoft.MinecraftUWP_1.17.4020.0_x64__8wekyb3d8bbwe
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftUWP_1.17.4020.0_x64__8wekyb3d8bbwe
Registering package
Deployment failed: Another user has already installed a packaged version of this app. An unpackaged version cannot replace this. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
App re-register failed:
System.Exception: Deployment failed: Another user has already installed a packaged version of this app. An unpackaged version cannot replace this. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562

**Comment by TresAbhi** [comment] 2021-09-20 14:51
Duplicate of #39

**Closed by TresAbhi** 2021-09-20 14:51 UTC
