### ISSUE TITLE
Error when starting the launcher after installation

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [BedrockLauncher/BedrockLauncher#176] opened 2022-03-23 13:51 UTC
HI, I just downloaded the launcher from the site and upon finishing the install and executing it, it says that there is a file that couldn't be found. I've tried with different methods but it is still the same problem.

The file that is missing is the "CefSharp.Core.Runtime.dll"
Ehm, translation of the log here: Cannot load the file or build "CefSharp.Core.Runtime.dll" nor any of the dependency. Cannot find the specified module.

About PC specifications, I can give them, but I have run more games, including Bedrock and Java Minecraft, so I don't believe it's a PC support problem.

I would apreciate the help. Thanks.

**Comment by TresAbhi** [comment] 2022-03-23 14:25
Duplicate of #84

**Closed by TresAbhi** 2022-03-23 14:25 UTC

**Comment by ArchDuque-Pancake** [comment] 2022-03-23 17:14
Thank you, now it works.
Btw, is there the possibility for me to help translate the proyect to spanish? I would like to help out.

**Comment by TresAbhi** [comment] 2022-03-24 02:47
https://crowdin.com/project/bedrocklauncher
