### ISSUE TITLE
Launcher fails to fetch `CefSharp.Core.Runtime.dll`

### ISSUE THREAD

**Issue by FrosticeYT** [BedrockLauncher/BedrockLauncher#109] opened 2021-12-04 11:53 UTC
![image](https://user-images.githubusercontent.com/90916297/144708466-355b7c75-a095-438d-86a0-e8c7e17a442a.png)

**Comment by NT690** [comment] 2021-12-06 23:15
Wouldn't this be a duplicate of #84? Or is there a difference between the two.

**Comment by Rayth** [comment] 2021-12-06 23:17
yep it's a duplicate

**Closed by Rayth** 2021-12-06 23:17 UTC
Labels: affects 0.0.2.6
